version: '3'
services:
  py311:
    image: srittau/gunicorn:3.11
    build:
      context: .
      args:
        - pyversion=3.11
  latest:
    image: srittau/gunicorn:latest
    build:
      context: .
      args:
        - pyversion=3.11
